### ISSUE TITLE
Android 4.4.4 Tv APK support

### ISSUE THREAD

**Issue by cutterchop** [deceptions/no#17]
Hello, i once reported this to the original dev, he made a version for 4.4.4 and it was a success but it wasn't a full version and it was only tested to see if it works, but you know what happened after it shut down, so if you can add support for 4.4.4 tv's is my request , not doing so limits the accessibility of the app and users that can use it on tv . please consider it !!!

**Comment by deceptions** [comment]
no

The overlapping panels library requires Android 21+ (5.0+) and so does the more recent ExoPlayer versions. Adding anything below Android 21 would therefore not only require a unique UI rework and a laundry list of bug-fixes, but also holding off updating the core library. Because of these reasons I will not support anything below Android 5.0.
