### ISSUE TITLE
A way to select to delete downloads/ the loading thing before downloading should be removed or faster 

### ISSUE THREAD

**Issue by Salamanka1212** [deceptions/no#35]
A way to select to delete downloads, i use file manager to delete in bulk🙃
the loading thing before downloading should be removed or faster because i can escape it  and it still downloads or goes to que

**Comment by deceptions** [comment]
As I already mentioned in your issue yesterday that select to delete is not getting developed (at least in the near future). It would be a waste of time compared to other features and fixes.

> the loading thing before downloading should be removed or faster because i can escape it and it still downloads or goes to que

I am not planning on changing that. The loading screen signals to the user that the button is working and responsive to prevent them from clicking twice. It would be preferable to make the loading on the button only instead of a popup, but that would entail tons of work fixing something already working. If I ever run out of stuff to do I might make it display the loading on the button.
