### ISSUE TITLE
That bar thing under watched episode

### ISSUE THREAD

**Issue by Ink25** [deceptions/no#65]
When we watch a episode completely in Kuro, that bar thing appears under that episode. 
![Screenshot_20211127_161837](https://user-images.githubusercontent.com/85929295/143688596-086a0678-0e9c-4757-86a5-808cce154d3e.png)

Maybe you should make it such that it appears on every episode we have watched, even if we haven't watched it on Kuro.

Btw, your are doing a great job 
Here, have some cookies and take your time 🍪🍪.

**Comment by jeyjai** [comment]
The white bar shows the percentage you've watched of the episode, if you do watch half you'll have half a bar. Originally the purple line you got around your episodes showed watched, which is why you can tap and hold on an episode to mark it. Before the project switched devs you could also tap and hold to make watched to unwatched.
