### ISSUE TITLE
Dubs have been replaced with subs

### ISSUE THREAD

**Issue by darthsinniious1989** [deceptions/no#75]
All the dubbed animes I put in my list have been replaced with the subs instead. The subbed versions show they aren't in my list but they show up there anyway. Like Naruto, I put the dubbed version instead & the sub pops up instead of the dub. I gotta search up the dub instead to watch it. Please fix this problem.

**Comment by deceptions** [comment]
If by list you are referring to MAL/AniList library that is intentional.
You can make any library page redirect to another page by holding and overriding the slug, in this case put **naruto-dub** (you can get the slugs by pressing the pencil icon).

I would recommend making Naruto a favorite by pressing the heart icon. Favorites show up in the homepage making searching redundant.
